#!/bin/bash

WATCH="*.cpp *.h"
STAMP_THIS=$(mktemp)
STAMP_CODE=$(mktemp)
WAIT=1

reset
touch $STAMP_THIS
touch -d "1 year ago" $STAMP_CODE

while :; do
	NEWER=0
	for i in $WATCH; do
		if [ $i -nt $STAMP_CODE ]; then
			NEWER=1
			break;
		fi
	done
	if [ $NEWER = 1 ]; then
		sleep 0.5
		touch $STAMP_CODE
		reset
		pkill -u 0 dparted
		rm -f dparted
		make -s || continue
		#make -s && main
		chown -R flatcap.flatcap /home/flatcap/work/partitions/gui
		./dparted &
		disown %1 2> /dev/null
		if [ 1 = 1 ]; then
			WORK=$(xdotool search --name "vi ")
			[ -n "$WORK" ] || continue
			for ((i=0; i < 10; i++)); do
				CURRENT=$(xdotool getactivewindow)
				if [ $CURRENT != $WORK ]; then
					xdotool search --name "vi " windowfocus
				fi
				sleep 0.5
			done
		fi
	fi

	[ $0 -nt $STAMP_THIS ] && exec $0

	sleep $WAIT
done


